### ISSUE TITLE
Tool crashes after multiple manual entries

### ISSUE THREAD

**Issue by soycold** [ThePacielloGroup/CCA-OSX#19] opened 2016-04-15 06:36 UTC
I'm a product designer at Facebook and would like to recommend this tool for all designers at Facebook to use. However, I'm reluctant to recommend this tool because it regularly crashes. I really want designers to use this tool over other tools out there because the color picker is a really convenient way to quickly test colors. And it's something non-designers (engineers, product managers, etc) can easily use since they wouldn't need to know the Hex. 

My workflow consists of toggling back and forth between the tool and Sketch (or Photoshop). I copy the hex value from Sketch and paste it into the foreground or background fields. It'll crash after about 6 times of manually entering a hex value into the fields.

**Comment by handcoding** [comment] 2016-05-24 15:43
For me, after pasting foreground & background colors about 20 times, I managed to get Colour Contrast Analyser to crash. (I’m running version 2.3 (0) on OS X 10.11.5.)

If it may help at all, I’ve also attached the contents of OS X’s crash log. 
[Colour Contrast Analyser 2-3-0 - crash report - 2016-05-24.txt](https://github.com/ThePacielloGroup/CCA-OSX/files/279868/Colour.Contrast.Analyser.2-3-0.-.crash.report.-.2016-05-24.txt)

**Comment by ferllings** [comment] 2017-10-09 15:49
I can't reproduce it. so I'll close it for now.

**Closed as completed by ferllings** 2017-10-09 15:49 UTC
Labels: bug
