### ISSUE TITLE
Picker is way off on monitor

### ISSUE THREAD

**Issue by JaaaPeee** [ThePacielloGroup/CCA-OSX#28] opened 2017-06-16 11:35 UTC
I have downloaded the current version and am working on a Mac Pro, on OS Sierra 10.12.5.
When I try to use the picker, it lands about 3.5” above the object I’m trying to measure.
Is there a way to make this align properly?

**Comment by ferllings** [comment] 2017-06-16 11:37
I noticed this bug, when using a secondary monitor.
Do you use a 2nd monitor or is it on the main monitor?

**Comment by JaaaPeee** [comment] 2017-06-16 11:40
Yes, it is on secondary monitor. To pass the 508 requirements, we must test on a PC monitor rather than a hi-res Mac monitor.

**Comment by ZoeBijl** [comment] 2017-08-02 12:29
Can confirm this is happening on secondary monitor.

**Comment by JaaaPeee** [comment] 2017-08-02 12:41
Confirmation wasn’t my major interest. . . solution is what I really need. This tool is useless for me with this problem.
Julien

**Comment by ferllings** [comment] 2017-09-28 07:35
Duplicate of https://github.com/ThePacielloGroup/CCA-OSX/issues/9

**Closed as completed by ferllings** 2017-09-28 07:35 UTC
Labels: duplicate
